// Code generated from Intl currency data (en locale). DO NOT EDIT.
//
// Currency metadata is resolved against the ICU en-locale tables:
//   - currencyNames          <- getName
//   - currencySymbols        <- getSymbol
//   - currencyFractionDigits <- getFractionDigits, with the ICU DEFAULT of 2
//                               for absent codes.
// Each helper falls back to a safe value for an unknown code (the code itself for
// names/symbols, 2 for fraction digits).
// Regenerate with gen_names.sh.

package currency

// defaultFractionDigits is the ICU DEFAULT fraction digits.
const defaultFractionDigits = 2

// currencyNames maps an ISO 4217 code to its English display name.
var currencyNames = map[string]string{
	"ADP": "Andorran Peseta",
	"AED": "United Arab Emirates Dirham",
	"AFA": "Afghan Afghani (1927–2002)",
	"AFN": "Afghan Afghani",
	"ALK": "Albanian Lek (1946–1965)",
	"ALL": "Albanian Lek",
	"AMD": "Armenian Dram",
	"ANG": "Netherlands Antillean Guilder",
	"AOA": "Angolan Kwanza",
	"AOK": "Angolan Kwanza (1977–1991)",
	"AON": "Angolan New Kwanza (1990–2000)",
	"AOR": "Angolan Readjusted Kwanza (1995–1999)",
	"ARA": "Argentine Austral",
	"ARL": "Argentine Peso Ley (1970–1983)",
	"ARM": "Argentine Peso (1881–1970)",
	"ARP": "Argentine Peso (1983–1985)",
	"ARS": "Argentine Peso",
	"ATS": "Austrian Schilling",
	"AUD": "Australian Dollar",
	"AWG": "Aruban Florin",
	"AZM": "Azerbaijani Manat (1993–2006)",
	"AZN": "Azerbaijani Manat",
	"BAD": "Bosnia-Herzegovina Dinar (1992–1994)",
	"BAM": "Bosnia-Herzegovina Convertible Mark",
	"BAN": "Bosnia-Herzegovina New Dinar (1994–1997)",
	"BBD": "Barbadian Dollar",
	"BDT": "Bangladeshi Taka",
	"BEC": "Belgian Franc (convertible)",
	"BEF": "Belgian Franc",
	"BEL": "Belgian Franc (financial)",
	"BGL": "Bulgarian Hard Lev",
	"BGM": "Bulgarian Socialist Lev",
	"BGN": "Bulgarian Lev",
	"BGO": "Bulgarian Lev (1879–1952)",
	"BHD": "Bahraini Dinar",
	"BIF": "Burundian Franc",
	"BMD": "Bermudan Dollar",
	"BND": "Brunei Dollar",
	"BOB": "Bolivian Boliviano",
	"BOL": "Bolivian Boliviano (1863–1963)",
	"BOP": "Bolivian Peso",
	"BOV": "Bolivian Mvdol",
	"BRB": "Brazilian New Cruzeiro (1967–1986)",
	"BRC": "Brazilian Cruzado (1986–1989)",
	"BRE": "Brazilian Cruzeiro (1990–1993)",
	"BRL": "Brazilian Real",
	"BRN": "Brazilian New Cruzado (1989–1990)",
	"BRR": "Brazilian Cruzeiro (1993–1994)",
	"BRZ": "Brazilian Cruzeiro (1942–1967)",
	"BSD": "Bahamian Dollar",
	"BTN": "Bhutanese Ngultrum",
	"BUK": "Burmese Kyat",
	"BWP": "Botswanan Pula",
	"BYB": "Belarusian Ruble (1994–1999)",
	"BYN": "Belarusian Ruble",
	"BYR": "Belarusian Ruble (2000–2016)",
	"BZD": "Belize Dollar",
	"CAD": "Canadian Dollar",
	"CDF": "Congolese Franc",
	"CHE": "WIR Euro",
	"CHF": "Swiss Franc",
	"CHW": "WIR Franc",
	"CLE": "Chilean Escudo",
	"CLF": "Chilean Unit of Account (UF)",
	"CLP": "Chilean Peso",
	"CNH": "Chinese Yuan (offshore)",
	"CNX": "Chinese People’s Bank Dollar",
	"CNY": "Chinese Yuan",
	"COP": "Colombian Peso",
	"COU": "Colombian Real Value Unit",
	"CRC": "Costa Rican Colón",
	"CSD": "Serbian Dinar (2002–2006)",
	"CSK": "Czechoslovak Hard Koruna",
	"CUC": "Cuban Convertible Peso",
	"CUP": "Cuban Peso",
	"CVE": "Cape Verdean Escudo",
	"CYP": "Cypriot Pound",
	"CZK": "Czech Koruna",
	"DDM": "East German Mark",
	"DEM": "German Mark",
	"DJF": "Djiboutian Franc",
	"DKK": "Danish Krone",
	"DOP": "Dominican Peso",
	"DZD": "Algerian Dinar",
	"ECS": "Ecuadorian Sucre",
	"ECV": "Ecuadorian Unit of Constant Value",
	"EEK": "Estonian Kroon",
	"EGP": "Egyptian Pound",
	"ERN": "Eritrean Nakfa",
	"ESA": "Spanish Peseta (A account)",
	"ESB": "Spanish Peseta (convertible account)",
	"ESP": "Spanish Peseta",
	"ETB": "Ethiopian Birr",
	"EUR": "Euro",
	"FIM": "Finnish Markka",
	"FJD": "Fijian Dollar",
	"FKP": "Falkland Islands Pound",
	"FRF": "French Franc",
	"GBP": "British Pound",
	"GEK": "Georgian Kupon Larit",
	"GEL": "Georgian Lari",
	"GHC": "Ghanaian Cedi (1979–2007)",
	"GHS": "Ghanaian Cedi",
	"GIP": "Gibraltar Pound",
	"GMD": "Gambian Dalasi",
	"GNF": "Guinean Franc",
	"GNS": "Guinean Syli",
	"GQE": "Equatorial Guinean Ekwele",
	"GRD": "Greek Drachma",
	"GTQ": "Guatemalan Quetzal",
	"GWE": "Portuguese Guinea Escudo",
	"GWP": "Guinea-Bissau Peso",
	"GYD": "Guyanaese Dollar",
	"HKD": "Hong Kong Dollar",
	"HNL": "Honduran Lempira",
	"HRD": "Croatian Dinar",
	"HRK": "Croatian Kuna",
	"HTG": "Haitian Gourde",
	"HUF": "Hungarian Forint",
	"IDR": "Indonesian Rupiah",
	"IEP": "Irish Pound",
	"ILP": "Israeli Pound",
	"ILR": "Israeli Shekel (1980–1985)",
	"ILS": "Israeli New Shekel",
	"INR": "Indian Rupee",
	"IQD": "Iraqi Dinar",
	"IRR": "Iranian Rial",
	"ISJ": "Icelandic Króna (1918–1981)",
	"ISK": "Icelandic Króna",
	"ITL": "Italian Lira",
	"JMD": "Jamaican Dollar",
	"JOD": "Jordanian Dinar",
	"JPY": "Japanese Yen",
	"KES": "Kenyan Shilling",
	"KGS": "Kyrgystani Som",
	"KHR": "Cambodian Riel",
	"KMF": "Comorian Franc",
	"KPW": "North Korean Won",
	"KRH": "South Korean Hwan (1953–1962)",
	"KRO": "South Korean Won (1945–1953)",
	"KRW": "South Korean Won",
	"KWD": "Kuwaiti Dinar",
	"KYD": "Cayman Islands Dollar",
	"KZT": "Kazakhstani Tenge",
	"LAK": "Laotian Kip",
	"LBP": "Lebanese Pound",
	"LKR": "Sri Lankan Rupee",
	"LRD": "Liberian Dollar",
	"LSL": "Lesotho Loti",
	"LTL": "Lithuanian Litas",
	"LTT": "Lithuanian Talonas",
	"LUC": "Luxembourgian Convertible Franc",
	"LUF": "Luxembourgian Franc",
	"LUL": "Luxembourg Financial Franc",
	"LVL": "Latvian Lats",
	"LVR": "Latvian Ruble",
	"LYD": "Libyan Dinar",
	"MAD": "Moroccan Dirham",
	"MAF": "Moroccan Franc",
	"MCF": "Monegasque Franc",
	"MDC": "Moldovan Cupon",
	"MDL": "Moldovan Leu",
	"MGA": "Malagasy Ariary",
	"MGF": "Malagasy Franc",
	"MKD": "Macedonian Denar",
	"MKN": "Macedonian Denar (1992–1993)",
	"MLF": "Malian Franc",
	"MMK": "Myanmar Kyat",
	"MNT": "Mongolian Tugrik",
	"MOP": "Macanese Pataca",
	"MRO": "Mauritanian Ouguiya (1973–2017)",
	"MRU": "Mauritanian Ouguiya",
	"MTL": "Maltese Lira",
	"MTP": "Maltese Pound",
	"MUR": "Mauritian Rupee",
	"MVP": "Maldivian Rupee (1947–1981)",
	"MVR": "Maldivian Rufiyaa",
	"MWK": "Malawian Kwacha",
	"MXN": "Mexican Peso",
	"MXP": "Mexican Silver Peso (1861–1992)",
	"MXV": "Mexican Investment Unit",
	"MYR": "Malaysian Ringgit",
	"MZE": "Mozambican Escudo",
	"MZM": "Mozambican Metical (1980–2006)",
	"MZN": "Mozambican Metical",
	"NAD": "Namibian Dollar",
	"NGN": "Nigerian Naira",
	"NIC": "Nicaraguan Córdoba (1988–1991)",
	"NIO": "Nicaraguan Córdoba",
	"NLG": "Dutch Guilder",
	"NOK": "Norwegian Krone",
	"NPR": "Nepalese Rupee",
	"NZD": "New Zealand Dollar",
	"OMR": "Omani Rial",
	"PAB": "Panamanian Balboa",
	"PEI": "Peruvian Inti",
	"PEN": "Peruvian Sol",
	"PES": "Peruvian Sol (1863–1965)",
	"PGK": "Papua New Guinean Kina",
	"PHP": "Philippine Peso",
	"PKR": "Pakistani Rupee",
	"PLN": "Polish Zloty",
	"PLZ": "Polish Zloty (1950–1995)",
	"PTE": "Portuguese Escudo",
	"PYG": "Paraguayan Guarani",
	"QAR": "Qatari Riyal",
	"RHD": "Rhodesian Dollar",
	"ROL": "Romanian Leu (1952–2006)",
	"RON": "Romanian Leu",
	"RSD": "Serbian Dinar",
	"RUB": "Russian Ruble",
	"RUR": "Russian Ruble (1991–1998)",
	"RWF": "Rwandan Franc",
	"SAR": "Saudi Riyal",
	"SBD": "Solomon Islands Dollar",
	"SCR": "Seychellois Rupee",
	"SDD": "Sudanese Dinar (1992–2007)",
	"SDG": "Sudanese Pound",
	"SDP": "Sudanese Pound (1957–1998)",
	"SEK": "Swedish Krona",
	"SGD": "Singapore Dollar",
	"SHP": "St. Helena Pound",
	"SIT": "Slovenian Tolar",
	"SKK": "Slovak Koruna",
	"SLE": "Sierra Leonean Leone",
	"SLL": "Sierra Leonean Leone (1964—2022)",
	"SOS": "Somali Shilling",
	"SRD": "Surinamese Dollar",
	"SRG": "Surinamese Guilder",
	"SSP": "South Sudanese Pound",
	"STD": "São Tomé & Príncipe Dobra (1977–2017)",
	"STN": "São Tomé & Príncipe Dobra",
	"SUR": "Soviet Rouble",
	"SVC": "Salvadoran Colón",
	"SYP": "Syrian Pound",
	"SZL": "Swazi Lilangeni",
	"THB": "Thai Baht",
	"TJR": "Tajikistani Ruble",
	"TJS": "Tajikistani Somoni",
	"TMM": "Turkmenistani Manat (1993–2009)",
	"TMT": "Turkmenistani Manat",
	"TND": "Tunisian Dinar",
	"TOP": "Tongan Paʻanga",
	"TPE": "Timorese Escudo",
	"TRL": "Turkish Lira (1922–2005)",
	"TRY": "Turkish Lira",
	"TTD": "Trinidad & Tobago Dollar",
	"TWD": "New Taiwan Dollar",
	"TZS": "Tanzanian Shilling",
	"UAH": "Ukrainian Hryvnia",
	"UAK": "Ukrainian Karbovanets",
	"UGS": "Ugandan Shilling (1966–1987)",
	"UGX": "Ugandan Shilling",
	"USD": "US Dollar",
	"USN": "US Dollar (Next day)",
	"USS": "US Dollar (Same day)",
	"UYI": "Uruguayan Peso (Indexed Units)",
	"UYP": "Uruguayan Peso (1975–1993)",
	"UYU": "Uruguayan Peso",
	"UYW": "Uruguayan Nominal Wage Index Unit",
	"UZS": "Uzbekistani Som",
	"VEB": "Venezuelan Bolívar (1871–2008)",
	"VED": "Bolívar Soberano",
	"VEF": "Venezuelan Bolívar (2008–2018)",
	"VES": "Venezuelan Bolívar",
	"VND": "Vietnamese Dong",
	"VNN": "Vietnamese Dong (1978–1985)",
	"VUV": "Vanuatu Vatu",
	"WST": "Samoan Tala",
	"XAF": "Central African CFA Franc",
	"XCD": "East Caribbean Dollar",
	"XCG": "Caribbean guilder",
	"XEU": "European Currency Unit",
	"XFO": "French Gold Franc",
	"XFU": "French UIC-Franc",
	"XOF": "West African CFA Franc",
	"XPF": "CFP Franc",
	"XRE": "RINET Funds",
	"YDD": "Yemeni Dinar",
	"YER": "Yemeni Rial",
	"YUD": "Yugoslavian Hard Dinar (1966–1990)",
	"YUM": "Yugoslavian New Dinar (1994–2002)",
	"YUN": "Yugoslavian Convertible Dinar (1990–1992)",
	"YUR": "Yugoslavian Reformed Dinar (1992–1993)",
	"ZAL": "South African Rand (financial)",
	"ZAR": "South African Rand",
	"ZMK": "Zambian Kwacha (1968–2012)",
	"ZMW": "Zambian Kwacha",
	"ZRN": "Zairean New Zaire (1993–1998)",
	"ZRZ": "Zairean Zaire (1971–1993)",
	"ZWD": "Zimbabwean Dollar (1980–2008)",
	"ZWG": "Zimbabwean Gold",
	"ZWL": "Zimbabwean Dollar (2009–2024)",
	"ZWR": "Zimbabwean Dollar (2008)",
}

// currencySymbols maps an ISO 4217 code to its narrow symbol (the code itself
// when ICU has no special symbol).
var currencySymbols = map[string]string{
	"ADP": "ADP",
	"AED": "AED",
	"AFA": "AFA",
	"AFN": "AFN",
	"ALK": "ALK",
	"ALL": "ALL",
	"AMD": "AMD",
	"ANG": "ANG",
	"AOA": "AOA",
	"AOK": "AOK",
	"AON": "AON",
	"AOR": "AOR",
	"ARA": "ARA",
	"ARL": "ARL",
	"ARM": "ARM",
	"ARP": "ARP",
	"ARS": "ARS",
	"ATS": "ATS",
	"AUD": "A$",
	"AWG": "AWG",
	"AZM": "AZM",
	"AZN": "AZN",
	"BAD": "BAD",
	"BAM": "BAM",
	"BAN": "BAN",
	"BBD": "BBD",
	"BDT": "BDT",
	"BEC": "BEC",
	"BEF": "BEF",
	"BEL": "BEL",
	"BGL": "BGL",
	"BGM": "BGM",
	"BGN": "BGN",
	"BGO": "BGO",
	"BHD": "BHD",
	"BIF": "BIF",
	"BMD": "BMD",
	"BND": "BND",
	"BOB": "BOB",
	"BOL": "BOL",
	"BOP": "BOP",
	"BOV": "BOV",
	"BRB": "BRB",
	"BRC": "BRC",
	"BRE": "BRE",
	"BRL": "R$",
	"BRN": "BRN",
	"BRR": "BRR",
	"BRZ": "BRZ",
	"BSD": "BSD",
	"BTN": "BTN",
	"BUK": "BUK",
	"BWP": "BWP",
	"BYB": "BYB",
	"BYN": "BYN",
	"BYR": "BYR",
	"BZD": "BZD",
	"CAD": "CA$",
	"CDF": "CDF",
	"CHE": "CHE",
	"CHF": "CHF",
	"CHW": "CHW",
	"CLE": "CLE",
	"CLF": "CLF",
	"CLP": "CLP",
	"CNH": "CNH",
	"CNX": "CNX",
	"CNY": "CN¥",
	"COP": "COP",
	"COU": "COU",
	"CRC": "CRC",
	"CSD": "CSD",
	"CSK": "CSK",
	"CUC": "CUC",
	"CUP": "CUP",
	"CVE": "CVE",
	"CYP": "CYP",
	"CZK": "CZK",
	"DDM": "DDM",
	"DEM": "DEM",
	"DJF": "DJF",
	"DKK": "DKK",
	"DOP": "DOP",
	"DZD": "DZD",
	"ECS": "ECS",
	"ECV": "ECV",
	"EEK": "EEK",
	"EGP": "EGP",
	"ERN": "ERN",
	"ESA": "ESA",
	"ESB": "ESB",
	"ESP": "ESP",
	"ETB": "ETB",
	"EUR": "€",
	"FIM": "FIM",
	"FJD": "FJD",
	"FKP": "FKP",
	"FRF": "FRF",
	"GBP": "£",
	"GEK": "GEK",
	"GEL": "GEL",
	"GHC": "GHC",
	"GHS": "GHS",
	"GIP": "GIP",
	"GMD": "GMD",
	"GNF": "GNF",
	"GNS": "GNS",
	"GQE": "GQE",
	"GRD": "GRD",
	"GTQ": "GTQ",
	"GWE": "GWE",
	"GWP": "GWP",
	"GYD": "GYD",
	"HKD": "HK$",
	"HNL": "HNL",
	"HRD": "HRD",
	"HRK": "HRK",
	"HTG": "HTG",
	"HUF": "HUF",
	"IDR": "IDR",
	"IEP": "IEP",
	"ILP": "ILP",
	"ILR": "ILR",
	"ILS": "₪",
	"INR": "₹",
	"IQD": "IQD",
	"IRR": "IRR",
	"ISJ": "ISJ",
	"ISK": "ISK",
	"ITL": "ITL",
	"JMD": "JMD",
	"JOD": "JOD",
	"JPY": "¥",
	"KES": "KES",
	"KGS": "KGS",
	"KHR": "KHR",
	"KMF": "KMF",
	"KPW": "KPW",
	"KRH": "KRH",
	"KRO": "KRO",
	"KRW": "₩",
	"KWD": "KWD",
	"KYD": "KYD",
	"KZT": "KZT",
	"LAK": "LAK",
	"LBP": "LBP",
	"LKR": "LKR",
	"LRD": "LRD",
	"LSL": "LSL",
	"LTL": "LTL",
	"LTT": "LTT",
	"LUC": "LUC",
	"LUF": "LUF",
	"LUL": "LUL",
	"LVL": "LVL",
	"LVR": "LVR",
	"LYD": "LYD",
	"MAD": "MAD",
	"MAF": "MAF",
	"MCF": "MCF",
	"MDC": "MDC",
	"MDL": "MDL",
	"MGA": "MGA",
	"MGF": "MGF",
	"MKD": "MKD",
	"MKN": "MKN",
	"MLF": "MLF",
	"MMK": "MMK",
	"MNT": "MNT",
	"MOP": "MOP",
	"MRO": "MRO",
	"MRU": "MRU",
	"MTL": "MTL",
	"MTP": "MTP",
	"MUR": "MUR",
	"MVP": "MVP",
	"MVR": "MVR",
	"MWK": "MWK",
	"MXN": "MX$",
	"MXP": "MXP",
	"MXV": "MXV",
	"MYR": "MYR",
	"MZE": "MZE",
	"MZM": "MZM",
	"MZN": "MZN",
	"NAD": "NAD",
	"NGN": "NGN",
	"NIC": "NIC",
	"NIO": "NIO",
	"NLG": "NLG",
	"NOK": "NOK",
	"NPR": "NPR",
	"NZD": "NZ$",
	"OMR": "OMR",
	"PAB": "PAB",
	"PEI": "PEI",
	"PEN": "PEN",
	"PES": "PES",
	"PGK": "PGK",
	"PHP": "₱",
	"PKR": "PKR",
	"PLN": "PLN",
	"PLZ": "PLZ",
	"PTE": "PTE",
	"PYG": "PYG",
	"QAR": "QAR",
	"RHD": "RHD",
	"ROL": "ROL",
	"RON": "RON",
	"RSD": "RSD",
	"RUB": "RUB",
	"RUR": "RUR",
	"RWF": "RWF",
	"SAR": "SAR",
	"SBD": "SBD",
	"SCR": "SCR",
	"SDD": "SDD",
	"SDG": "SDG",
	"SDP": "SDP",
	"SEK": "SEK",
	"SGD": "SGD",
	"SHP": "SHP",
	"SIT": "SIT",
	"SKK": "SKK",
	"SLE": "SLE",
	"SLL": "SLL",
	"SOS": "SOS",
	"SRD": "SRD",
	"SRG": "SRG",
	"SSP": "SSP",
	"STD": "STD",
	"STN": "STN",
	"SUR": "SUR",
	"SVC": "SVC",
	"SYP": "SYP",
	"SZL": "SZL",
	"THB": "THB",
	"TJR": "TJR",
	"TJS": "TJS",
	"TMM": "TMM",
	"TMT": "TMT",
	"TND": "TND",
	"TOP": "TOP",
	"TPE": "TPE",
	"TRL": "TRL",
	"TRY": "TRY",
	"TTD": "TTD",
	"TWD": "NT$",
	"TZS": "TZS",
	"UAH": "UAH",
	"UAK": "UAK",
	"UGS": "UGS",
	"UGX": "UGX",
	"USD": "$",
	"USN": "USN",
	"USS": "USS",
	"UYI": "UYI",
	"UYP": "UYP",
	"UYU": "UYU",
	"UYW": "UYW",
	"UZS": "UZS",
	"VEB": "VEB",
	"VED": "VED",
	"VEF": "VEF",
	"VES": "VES",
	"VND": "₫",
	"VNN": "VNN",
	"VUV": "VUV",
	"WST": "WST",
	"XAF": "FCFA",
	"XCD": "EC$",
	"XCG": "Cg.",
	"XEU": "XEU",
	"XFO": "XFO",
	"XFU": "XFU",
	"XOF": "F CFA",
	"XPF": "CFPF",
	"XRE": "XRE",
	"YDD": "YDD",
	"YER": "YER",
	"YUD": "YUD",
	"YUM": "YUM",
	"YUN": "YUN",
	"YUR": "YUR",
	"ZAL": "ZAL",
	"ZAR": "ZAR",
	"ZMK": "ZMK",
	"ZMW": "ZMW",
	"ZRN": "ZRN",
	"ZRZ": "ZRZ",
	"ZWD": "ZWD",
	"ZWG": "ZWG",
	"ZWL": "ZWL",
	"ZWR": "ZWR",
}

// currencyFractionDigits maps an ISO 4217 code to its fraction digits when it
// differs from the default (2). Codes absent here use defaultFractionDigits.
var currencyFractionDigits = map[string]int{
	"ADP": 0,
	"AFN": 0,
	"ALL": 0,
	"BHD": 3,
	"BIF": 0,
	"BYR": 0,
	"CLF": 4,
	"CLP": 0,
	"DJF": 0,
	"ESP": 0,
	"GNF": 0,
	"IQD": 0,
	"IRR": 0,
	"ISK": 0,
	"ITL": 0,
	"JOD": 3,
	"JPY": 0,
	"KMF": 0,
	"KPW": 0,
	"KRW": 0,
	"KWD": 3,
	"LAK": 0,
	"LBP": 0,
	"LUF": 0,
	"LYD": 3,
	"MGA": 0,
	"MGF": 0,
	"MMK": 0,
	"MRO": 0,
	"OMR": 3,
	"PYG": 0,
	"RSD": 0,
	"RWF": 0,
	"SLL": 0,
	"SOS": 0,
	"STD": 0,
	"SYP": 0,
	"TMM": 0,
	"TND": 3,
	"TRL": 0,
	"UGX": 0,
	"UYI": 0,
	"UYW": 4,
	"VND": 0,
	"VUV": 0,
	"XAF": 0,
	"XOF": 0,
	"XPF": 0,
	"YER": 0,
	"ZMK": 0,
	"ZWD": 0,
}

// DisplayName returns the English currency name for a code, or the code itself
// when the table has no entry.
func DisplayName(code string) string {
	if n, ok := currencyNames[code]; ok {
		return n
	}
	return code
}

// Symbol returns the narrow currency symbol for a code, or the code itself when
// the table has no entry.
func Symbol(code string) string {
	if s, ok := currencySymbols[code]; ok {
		return s
	}
	return code
}

// FractionDigits returns the ICU fraction digits for a code, defaulting to 2.
func FractionDigits(code string) int {
	if d, ok := currencyFractionDigits[code]; ok {
		return d
	}
	return defaultFractionDigits
}
