package apidoc

import (
	"net/http"

	"github.com/swaggo/swag"

	httpSwagger "github.com/swaggo/http-swagger/v2"

	// Blank-import the generated docs so their init() registers the spec with
	// swaggo's global registry, making it available to swag.ReadDoc() (the raw
	// spec endpoint) and the http-swagger UI handler. docs.go is generated by
	// `swag init`.
	_ "github.com/econumo/econumo/internal/web/apidoc/docs"

	"github.com/econumo/econumo/internal/web/router"
)

// RegisterAPI returns a router.RegisterAPI that mounts the Swagger UI at
// /api/doc and the raw OpenAPI spec at /api/doc.json. Both are public — they are
// mounted bare (no JWT wrapper), so they are
// reachable without authentication. The router's global chain
// (requestid/recover/cors/timezone) still applies since they live under /api.
func RegisterAPI() router.RegisterAPI {
	return func(mux *http.ServeMux) {
		// Raw spec: serve the generated OpenAPI JSON registered by docs.init().
		mux.HandleFunc("GET /api/doc.json", specHandler)

		// Swagger UI. The trailing-slash pattern serves the UI assets; the bare
		// /api/doc redirects into it. The UI fetches the spec from /api/doc.json.
		mux.Handle("GET /api/doc", http.RedirectHandler("/api/doc/", http.StatusMovedPermanently))
		mux.Handle("GET /api/doc/", httpSwagger.Handler(httpSwagger.URL("/api/doc.json")))
	}
}

// specHandler writes the generated OpenAPI document as JSON. swag.ReadDoc()
// returns the spec registered by the generated docs package's init().
func specHandler(w http.ResponseWriter, _ *http.Request) {
	doc, err := swag.ReadDoc()
	if err != nil {
		http.Error(w, "swagger spec unavailable", http.StatusInternalServerError)
		return
	}
	w.Header().Set("Content-Type", "application/json")
	_, _ = w.Write([]byte(doc))
}
