package user

import (
	"time"

	"github.com/econumo/econumo/internal/shared/vo"
)

// passwordRequestTTL is how long a reset code stays valid.
const passwordRequestTTL = 10 * time.Minute

// PasswordRequest is a pending password-reset code for a user. The code itself is
// generated by the application layer (crypto lives outside the domain) and passed
// in. expiredAt is createdAt + passwordRequestTTL.
type PasswordRequest struct {
	id        vo.Id
	userID    vo.Id
	code      string
	createdAt time.Time
	updatedAt time.Time
	expiredAt time.Time
}

// NewPasswordRequest builds a fresh reset request expiring 10 minutes from now.
func NewPasswordRequest(id, userID vo.Id, code string, now time.Time) *PasswordRequest {
	return &PasswordRequest{
		id:        id,
		userID:    userID,
		code:      code,
		createdAt: now,
		updatedAt: now,
		expiredAt: now.Add(passwordRequestTTL),
	}
}

func ReconstitutePasswordRequest(id, userID vo.Id, code string, createdAt, updatedAt, expiredAt time.Time) *PasswordRequest {
	return &PasswordRequest{
		id:        id,
		userID:    userID,
		code:      code,
		createdAt: createdAt,
		updatedAt: updatedAt,
		expiredAt: expiredAt,
	}
}

func (r *PasswordRequest) Id() vo.Id { return r.id }

func (r *PasswordRequest) UserId() vo.Id { return r.userID }

func (r *PasswordRequest) Code() string { return r.code }

func (r *PasswordRequest) CreatedAt() time.Time { return r.createdAt }

func (r *PasswordRequest) UpdatedAt() time.Time { return r.updatedAt }

func (r *PasswordRequest) ExpiredAt() time.Time { return r.expiredAt }

// IsExpired reports whether the code is no longer valid at the given time.
func (r *PasswordRequest) IsExpired(now time.Time) bool { return now.After(r.expiredAt) }
