package user

import (
	"time"

	"github.com/econumo/econumo/internal/shared/vo"
)

// passwordRequestTTL is how long a reset code stays valid.
const passwordRequestTTL = 10 * time.Minute

// PasswordRequest is a pending password-reset code for a user. The code itself is
// generated by the application layer (crypto lives outside the domain) and passed
// in. ExpiredAt is CreatedAt + passwordRequestTTL. Fields are exported for direct
// read access; the request has no mutators (it is replaced, not updated).
type PasswordRequest struct {
	ID        vo.Id
	UserID    vo.Id
	Code      string
	CreatedAt time.Time
	UpdatedAt time.Time
	ExpiredAt time.Time
}

// NewPasswordRequest builds a fresh reset request expiring 10 minutes from now.
func NewPasswordRequest(id, userID vo.Id, code string, now time.Time) *PasswordRequest {
	return &PasswordRequest{
		ID:        id,
		UserID:    userID,
		Code:      code,
		CreatedAt: now,
		UpdatedAt: now,
		ExpiredAt: now.Add(passwordRequestTTL),
	}
}

// IsExpired reports whether the code is no longer valid at the given time.
func (r *PasswordRequest) IsExpired(now time.Time) bool { return now.After(r.ExpiredAt) }
